import "./globals.css";
import { ReduxProvider } from "./redux/provider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export const metadata = {
  title: "LeetCode Collections",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider>
        <ToastContainer position="top-left" autoClose={2000} theme="colored" />
      </body>
    </html>
  );
}
